### ISSUE TITLE
大佬求指点一下思路，seata启动报错

### ISSUE THREAD

**Issue by arraycto** [lidong1665/seata-spring-boot-dubbo-nacos-shardingsphere-examples#3]
seata:1.2.0
nacos:1.1.4

seata的配置能顺利入nacos中
但是启动seata的服务出错，启动命令

随后启动seata报错，启动命令

./seata-server.sh -p 8091 -h 127.0.0.1 -m db

log如下

```

15:27:39,985 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]
15:27:39,985 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:27:39,985 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6cc4c815 - Registering current configuration as safe fallback point

2020-07-01 15:27:40.174 INFO [main]io.seata.config.FileConfiguration.<init>:121 -The configuration file used is registry.conf
2020-07-01 15:27:40.754 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.file.session.FileSessionManager has already been loaded, skipped
2020-07-01 15:27:40.755 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.db.session.DataBaseSessionManager has already been loaded, skipped
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instanition: io.seata.common.loader.ExtensionDefinition@218540c9, class: interface io.seata.server.session.SessionManager)  could not be instantiated: the name of service provider for [io.seata.core.store.db.DataSourceGenname is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:404)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:393)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:358)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
	at io.seata.server.Server.main(Server.java:75)
Caused by: java.lang.IllegalArgumentException: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:353)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:98)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:84)
	at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:81)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:560)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:400)
	... 7 more

[root@iZ8vbido9l61vd7k054mitZ bin]# ps -ef|grep seata
root     25274  8073  0 15:28 pts/1    00:00:00 grep --color=auto seata
[root@iZ8vbido9l61vd7k054mitZ bin]# 
 
```

烦请大佬指点一下思路，搞了好久，无果

**Comment by lidong1665** [comment]
看一下的你的配置中心

**Comment by arraycto** [comment]
![QQ截图20200703111325](https://user-images.githubusercontent.com/37463247/86427967-2d9aa700-bd1e-11ea-8f51-42f8248f853d.png)

**Comment by arraycto** [comment]
[nacos_config_export_20200703111224.zip](https://github.com/lidong1665/seata-spring-boot-dubbo-nacos-shardingsphere-examples/files/4867568/nacos_config_export_20200703111224.zip)
大佬，我导出了一份，请查看。

**Comment by arraycto** [comment]
可以直接导入nacos中更加详情。

**Comment by arraycto** [comment]
file.conf

```
## seata-service
service {
  #交易服务组映射 的组名称必须要与客户端一致 my_test_tx_group  seata-server必须要与registrt.conf 一致
  #transaction service group mapping
  #TODO 修改 hxlh_tx_group为自己设置的事务组名称，seata-server不是事务组的名称，这里可以随便起名
  vgroupMapping.my_test_tx_group = "seata-server"
  #only support when registry.type=file, please don't set multiple addresses
  #TODO 这里设置ip, 一般不用改 因为我是安装在内网了
  default.grouplist = "192.168.186.128:8091"
  #disable seata
  disableGlobalTransaction = false
}


## transaction log store, only used in seata-server
store {
  ## store mode: file、db
  ##TODO 修改为数据库类型
  mode = "db"

  ## file store property
  file {
    ## store location dir
    dir = "sessionStore"
    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    maxBranchSessionSize = 16384
    # globe session size , if exceeded throws exceptions
    maxGlobalSessionSize = 512
    # file buffer size , if exceeded allocate new buffer
    fileWriteBufferCacheSize = 16384
    # when recover batch read size
    sessionReloadReadSize = 100
    # async, sync
    flushDiskMode = async
  }

  ## database store property
  #TODO 下面这一堆就安装自己MySQL去改就行了，使用的库便是我们上面创建的seata库
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "druid"
    ## mysql/oracle/postgresql/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://127.0.0.1:3306/seata"
    user = "root"
    password = "root"
    minConn = 5
    maxConn = 30
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
    maxWait = 5000
  }
}

```



regitstry.conf

```

registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  #TODO 配置为nacos
  type = "nacos"

#TODO 设置你自己的nacos即可
  nacos {
    application = "seata-server"
    serverAddr = "192.168.186.128:8848"
    namespace = "a70f5328-e56c-47f8-984f-da7f134d9151"
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = 0
    password = ""
    cluster = "default"
    timeout = 0
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "192.168.186.128:8848"
    namespace = "a70f5328-e56c-47f8-984f-da7f134d9151"
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}


```

**Comment by arraycto** [comment]
@songdeweigit 亲，您的seata是1.2 成功了？？？？？？

**Comment by songdeweigit** [comment]
@arraycto  可以正常启动啊

**Comment by arraycto** [comment]
搞了半个月无果。麻烦您看看上面的配置文件，麻烦指点一下，是否哪里不同，跪谢~@songdeweigit

**Comment by lidong1665** [comment]
@arraycto 你的问题解决了吗，看你的配置是没问题的

**Comment by arraycto** [comment]
还是没解决，是不是版本问题，我用的seata1.2.0   centos7.5   jdk8

**Comment by arraycto** [comment]
nacos1.2.1 和nacos1.1.4 均报错，如一楼

**Comment by leihuangyan** [comment]
请问有解决找到解决办法了吗？

**Comment by lidong1665** [comment]
> 请问有解决找到解决办法了吗？

你也遇到同样的问题吗？具体错误贴一下，

**Comment by leihuangyan** [comment]
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@20222904, class: interface io.seata.server.session.SessionManager)  could not be instantiated: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:404)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:393)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:358)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
	at io.seata.server.Server.main(Server.java:75)
Caused by: java.lang.IllegalArgumentException: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:353)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:98)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:84)
	at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:81)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:560)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:400)
	... 7 more

**Comment by leihuangyan** [comment]
> > 请问有解决找到解决办法了吗？
> 
> 你也遇到同样的问题吗？具体错误贴一下，

有解决办法吗

**Comment by leihuangyan** [comment]
> > 请问有解决找到解决办法了吗？
> 
> 你也遇到同样的问题吗？具体错误贴一下，

有解决办法吗

> > > 请问有解决找到解决办法了吗？
> > 
> > 
> > 你也遇到同样的问题吗？具体错误贴一下，
> 
> 有解决办法吗

错误贴出来了

**Comment by leihuangyan** [comment]
我问题解决了，重新提交了config.txt文件
